
package vista;

import DAO.SqlUsuarios;
import java.awt.Color;
import javax.swing.JOptionPane;
import modelo.hash;
import modelo.usuarios;

/**
 *
 * @author Usuario
 */
public class crearCuenta extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public crearCuenta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        logo = new javax.swing.JLabel();
        contraseña = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        username = new javax.swing.JTextField();
        nombredeusuario = new javax.swing.JLabel();
        ccPanel = new javax.swing.JPanel();
        cclabel = new javax.swing.JLabel();
        confirmarcontraseña = new javax.swing.JLabel();
        conpass = new javax.swing.JPasswordField();
        bgimage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("D&D Calculator");
        setLocationByPlatform(true);
        setName("login"); // NOI18N
        setPreferredSize(new java.awt.Dimension(900, 600));
        setResizable(false);

        bg.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bg.setFocusable(false);
        bg.setMinimumSize(new java.awt.Dimension(900, 600));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));
        jSeparator1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 20));
        bg.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 870, 40));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Imagenes/alt big logo nb.png"))); // NOI18N
        bg.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 150));

        contraseña.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 24)); // NOI18N
        contraseña.setForeground(new java.awt.Color(255, 255, 255));
        contraseña.setText("Contraseña");
        bg.add(contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 290, 80));

        pass.setBackground(new java.awt.Color(0, 0, 0));
        pass.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        pass.setForeground(new java.awt.Color(204, 204, 204));
        pass.setText("********");
        pass.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(102, 102, 102)));
        pass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passMousePressed(evt);
            }
        });
        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });
        bg.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 270, 50));

        username.setBackground(new java.awt.Color(0, 0, 0));
        username.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        username.setForeground(new java.awt.Color(204, 204, 204));
        username.setText("Ingrese nombre de usuario");
        username.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(102, 102, 102)));
        username.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                usernameMousePressed(evt);
            }
        });
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        bg.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 270, 50));

        nombredeusuario.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 24)); // NOI18N
        nombredeusuario.setForeground(new java.awt.Color(255, 255, 255));
        nombredeusuario.setText("Nombre de usuario");
        bg.add(nombredeusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 300, 80));

        ccPanel.setBackground(new java.awt.Color(0, 0, 0));

        cclabel.setBackground(new java.awt.Color(0, 0, 0));
        cclabel.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 28)); // NOI18N
        cclabel.setForeground(new java.awt.Color(255, 255, 255));
        cclabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cclabel.setText("Crear Cuenta");
        cclabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(102, 102, 102)));
        cclabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cclabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cclabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ccPanelLayout = new javax.swing.GroupLayout(ccPanel);
        ccPanel.setLayout(ccPanelLayout);
        ccPanelLayout.setHorizontalGroup(
            ccPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ccPanelLayout.createSequentialGroup()
                .addComponent(cclabel, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                .addContainerGap())
        );
        ccPanelLayout.setVerticalGroup(
            ccPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cclabel, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        bg.add(ccPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 480, 330, 60));

        confirmarcontraseña.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 24)); // NOI18N
        confirmarcontraseña.setForeground(new java.awt.Color(255, 255, 255));
        confirmarcontraseña.setText("Confirmar Contraseña");
        bg.add(confirmarcontraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 310, 80));

        conpass.setBackground(new java.awt.Color(0, 0, 0));
        conpass.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        conpass.setForeground(new java.awt.Color(204, 204, 204));
        conpass.setText("********");
        conpass.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(102, 102, 102)));
        conpass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                conpassMousePressed(evt);
            }
        });
        conpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conpassActionPerformed(evt);
            }
        });
        bg.add(conpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 270, 50));

        bgimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Imagenes/bgdnd.png"))); // NOI18N
        bg.add(bgimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void cclabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cclabelMouseClicked

        SqlUsuarios modSql = new SqlUsuarios();
        usuarios mod = new usuarios();

        String passText = new String(pass.getPassword());
        String passcon = new String(conpass.getPassword());

        if (username.getText().equals("") || pass.equals("") || conpass.equals("") || String.valueOf(pass.getPassword()).equals("********") || String.valueOf(conpass.getPassword()).equals("********") || username.getText().equals("Ingrese nombre de usuario")) {
            JOptionPane.showMessageDialog(null, "Por favor, llene todos los campos");
        } else {

            if (passText.equals(passcon)) {

                if (modSql.ValidacionUsuario(username.getText()) == 0) {

                

                String nuevoPass = hash.sha1(passText);

                mod.setUsuario(username.getText());
                mod.setPassword(nuevoPass);
                mod.setId_tipo(1);

                if (modSql.registrar(mod)) {
                    JOptionPane.showMessageDialog(null, "Se ha registrado con exito");
                    limpiar();
                    new login().setVisible(true);
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "No se pudo registrar, quiza otra vez");
                }
                } else {
                JOptionPane.showMessageDialog(null, "El nombre de usuario ya esta siendo usado por otro aventurero");
                }
        }else {
            JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden");
        }
    }
        
    }//GEN-LAST:event_cclabelMouseClicked

    private void limpiar(){
        pass.setText("");
        conpass.setText("");
        username.setText("");
    }
    private void conpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conpassActionPerformed

    private void usernameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernameMousePressed
        if(username.getText().equals("Ingrese nombre de usuario")){
         username.setText("");
        }
        
        if(String.valueOf(pass.getPassword()).isEmpty()){
         pass.setText("********");
        }
        
        if(String.valueOf(conpass.getPassword()).isEmpty()){
         conpass.setText("********");
        }
    }//GEN-LAST:event_usernameMousePressed

    private void passMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passMousePressed
        if(String.valueOf(pass.getPassword()).equals("********")){
         pass.setText("");
        }
        
        if(username.getText().isEmpty()){
         username.setText("Ingrese nombre de usuario");
        }
        
        if(String.valueOf(conpass.getPassword()).isEmpty()){
         conpass.setText("********");
        }
    }//GEN-LAST:event_passMousePressed

    private void conpassMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_conpassMousePressed
        if(String.valueOf(conpass.getPassword()).equals("********")){
         conpass.setText("");
        }
        
        if(username.getText().isEmpty()){
         username.setText("Ingrese nombre de usuario");
        }
         
        if(String.valueOf(pass.getPassword()).isEmpty()){
         pass.setText("********");
        }
    }//GEN-LAST:event_conpassMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(crearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(crearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(crearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(crearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new crearCuenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel bgimage;
    private javax.swing.JPanel ccPanel;
    private javax.swing.JLabel cclabel;
    private javax.swing.JLabel confirmarcontraseña;
    private javax.swing.JPasswordField conpass;
    private javax.swing.JLabel contraseña;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel nombredeusuario;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables

}
