/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import DAO.SqlUsuarios;
import javax.swing.JOptionPane;
import modelo.hash;
import modelo.usuarios;

/**
 *
 * @author Usuario
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        logo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Passwrd = new javax.swing.JPasswordField();
        username = new javax.swing.JTextField();
        lgnombredeusuario = new javax.swing.JLabel();
        isPanel = new javax.swing.JPanel();
        isLabel = new javax.swing.JLabel();
        ccPanel = new javax.swing.JPanel();
        cclabel = new javax.swing.JLabel();
        bgimage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("D&D Calculator");
        setLocationByPlatform(true);
        setName("login"); // NOI18N
        setPreferredSize(new java.awt.Dimension(900, 600));
        setResizable(false);

        bg.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bg.setFocusable(false);
        bg.setMinimumSize(new java.awt.Dimension(900, 600));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));
        jSeparator1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 20));
        bg.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 870, 40));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Imagenes/alt big logo nb.png"))); // NOI18N
        bg.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 150));

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Contraseña");
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 470, 80));

        Passwrd.setBackground(new java.awt.Color(0, 0, 0));
        Passwrd.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        Passwrd.setForeground(new java.awt.Color(204, 204, 204));
        Passwrd.setText("********");
        Passwrd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(102, 102, 102)));
        Passwrd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PasswrdMousePressed(evt);
            }
        });
        Passwrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswrdActionPerformed(evt);
            }
        });
        bg.add(Passwrd, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 330, 60));

        username.setBackground(new java.awt.Color(0, 0, 0));
        username.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        username.setForeground(new java.awt.Color(204, 204, 204));
        username.setText("Ingrese nombre de usuario");
        username.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(102, 102, 102)));
        username.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                usernameMousePressed(evt);
            }
        });
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        bg.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 330, 50));

        lgnombredeusuario.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 36)); // NOI18N
        lgnombredeusuario.setForeground(new java.awt.Color(255, 255, 255));
        lgnombredeusuario.setText("Nombre de usuario");
        bg.add(lgnombredeusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 470, 80));

        isPanel.setBackground(new java.awt.Color(0, 0, 0));

        isLabel.setBackground(new java.awt.Color(0, 0, 0));
        isLabel.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 28)); // NOI18N
        isLabel.setForeground(new java.awt.Color(255, 255, 255));
        isLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        isLabel.setText("Iniciar sesion");
        isLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(102, 102, 102)));
        isLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        isLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                isLabelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout isPanelLayout = new javax.swing.GroupLayout(isPanel);
        isPanel.setLayout(isPanelLayout);
        isPanelLayout.setHorizontalGroup(
            isPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(isLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
        );
        isPanelLayout.setVerticalGroup(
            isPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(isLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        bg.add(isPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 330, 60));

        ccPanel.setBackground(new java.awt.Color(0, 0, 0));

        cclabel.setBackground(new java.awt.Color(0, 0, 0));
        cclabel.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 28)); // NOI18N
        cclabel.setForeground(new java.awt.Color(255, 255, 255));
        cclabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cclabel.setText("Crear Cuenta");
        cclabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(102, 102, 102)));
        cclabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cclabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cclabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ccPanelLayout = new javax.swing.GroupLayout(ccPanel);
        ccPanel.setLayout(ccPanelLayout);
        ccPanelLayout.setHorizontalGroup(
            ccPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ccPanelLayout.createSequentialGroup()
                .addComponent(cclabel, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                .addContainerGap())
        );
        ccPanelLayout.setVerticalGroup(
            ccPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cclabel, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        bg.add(ccPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 480, 330, 60));

        bgimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Imagenes/bgdnd.png"))); // NOI18N
        bg.add(bgimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PasswrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswrdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswrdActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void cclabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cclabelMouseClicked
       new crearCuenta().setVisible(true);
       dispose();
    }//GEN-LAST:event_cclabelMouseClicked

    private void usernameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernameMousePressed
        if(username.getText().equals("Ingrese nombre de usuario")){
         username.setText("");
        }
        
        if(String.valueOf(Passwrd.getPassword()).isEmpty()){
         Passwrd.setText("********");
        }
    }//GEN-LAST:event_usernameMousePressed

    private void PasswrdMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswrdMousePressed
        if(String.valueOf(Passwrd.getPassword()).equals("********")){
         Passwrd.setText("");
        }
        
        if(username.getText().isEmpty()){
         username.setText("Ingrese nombre de usuario");
        }
    }//GEN-LAST:event_PasswrdMousePressed

    private void isLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isLabelMousePressed
       
        SqlUsuarios modSql= new SqlUsuarios();
        usuarios mod = new usuarios();
        
        String passStr = new String(Passwrd.getPassword());
        
        if (!username.getText().equals("") && !Passwrd.equals("") || !String.valueOf(Passwrd.getPassword()).equals("********")&& !username.getText().equals("Ingrese nombre de usuario")) {
            String nuevoPass= hash.sha1(passStr);
            
            mod.setUsuario(username.getText());
            mod.setPassword(nuevoPass);
            
            if(modSql.login(mod)){
                new Personaje().setVisible(true);
                this.dispose();
            } else{
                JOptionPane.showMessageDialog(null,"Datos Incorrectos");
            }
            
        } else{
            JOptionPane.showMessageDialog(null,"Debe ingresar datos, Aventurero (CRINGE)");
        }
        
    }//GEN-LAST:event_isLabelMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Passwrd;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel bgimage;
    private javax.swing.JPanel ccPanel;
    private javax.swing.JLabel cclabel;
    private javax.swing.JLabel isLabel;
    private javax.swing.JPanel isPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lgnombredeusuario;
    private javax.swing.JLabel logo;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
